ALTER TABLE Work
    ADD WorkID BIGINT PRIMARY KEY AUTO_INCREMENT;

ALTER TABLE Student
    ADD WorkID BIGINT NOT NULL;
ALTER TABLE Student
    ADD CONSTRAINT FK_WorkID FOREIGN KEY (WorkID) REFERENCES Work(WorkID);
